export const projects = [
  {
    id: 1,
    title: "Vibrant",
    detailsUrl: "vibrant",
    description:
      "A CLI tool that detects AI-generated code patterns before they ship to production.",
    longDescription:
      "Vibrant is a CLI tool that detects vibecoded patterns — code that looks like it was generated by AI without proper review. It catches shortcuts, placeholders, security issues, and anti-patterns that slip through when developers use AI assistants. Features include 15+ static analysis rules, AI-powered analysis with multiple LLM providers, auto-fix capabilities, and humorous feedback when issues are found.",
    image: "/projects/vibrant.webp",
    href: "https://www.npmjs.com/package/vibrant-cli",
    repository: "https://github.com/francogalfre/vibrant",
    tags: ["TypeScript", "Node.js", "AI", "CLI", "Security"],
  },
  {
    id: 2,
    title: "Patitas",
    detailsUrl: "patitas",
    description: "A platform connecting pets with adoptive families.",
    image: "/projects/patitas.webp",
    href: "https://www.patitas.site/",
    repository: "https://github.com/francogalfre/patitas",
    tags: ["Next.js", "Node.js", "Tailwind", "Typescript", "PostgreSQL"],
  },
  {
    id: 3,
    title: "Freelanceo",
    detailsUrl: "freelanceo",
    description:
      "An intuitive dashboard for freelancers to manage projects, clients, and finances.",
    longDescription:
      "A complete dashboard for freelancers to organize clients, projects, and daily tasks, while visualizing earnings and progress through interactive charts. Built with Next.js, TypeScript, Tailwind, and PostgreSQL for speed and clarity.",
    image: "/projects/freelanceo.webp",
    image2: "/projects/freelanceo2.webp",
    href: "https://www.freelanceo.site",
    repository: "https://github.com/francogalfre/freelanceo",
    tags: ["Next.js", "Node.js", "Tailwind", "Typescript", "PostgreSQL"],
  },
  {
    id: 4,
    title: "Astrotips",
    detailsUrl: "astrotips",
    description:
      "A fast website with tips and interactive examples for learning Astro.",
    longDescription:
      "A modern platform offering tips, best practices, and interactive examples to help developers learn Astro efficiently. Built with Astro, TypeScript, and Tailwind, focusing on performance and clean design.",
    image: "/projects/astrotips.webp",
    image2: "/projects/astrotips2.webp",
    href: "https://astrotips.vercel.app/",
    repository: "https://github.com/francogalfre/astrotips",
    tags: ["Astro", "Tailwind", "Typescript"],
  },
  {
    id: 5,
    title: "Promptsmith",
    detailsUrl: "promptsmith",
    description: "A type-safe prompt builder for the Vercel AI SDK.",
    image: "/projects/promptsmith.webp",
    href: "https://promptsmith.galfrevn.com/",
    repository: "https://github.com/galfrevn/promptsmith",
    tags: ["Next.js", "Tailwind", "Typescript", "Motion"],
  },
  {
    id: 6,
    title: "Github Profile Explorer",
    detailsUrl: "github-profile-explorer",
    description:
      "A fast tool to explore GitHub profiles with dark/light themes.",
    image: "/projects/github-profile.webp",
    href: "https://github-profiles-explorer.vercel.app/",
    repository: "https://github.com/francogalfre/github-profile-explorer",
    tags: ["React", "Javascript", "CSS", "Github API"],
  },
];
